apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-config
    namespace: vpn-gateway
stringData:
    TZ: ENC[AES256_GCM,data:SpPI6u1i30jX2Vz8VQ==,iv:dwS/PAICIL9qDjfKakrYv/rYD0v3GdfOFzyQYSIuBmA=,tag:dODfZoCl+/UCL+ImTXtfvw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data://C3bM2WKw==,iv:4MJwSIDReRmn8x8YYOGk0CHO8pb7zydw5j73+tCJMF4=,tag:DIvPNmfiU4v8LifmSc7hrg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:sc/CwRKO,iv:nwhhAFQS2596pkHgR9dh2DEPkTYz2RHH+LZCMj5/V44=,tag:Mdx6MGgyMNxl37PclSbcNQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:GDKYR1JpsS1689lxTJRpB+v1E6CJEs2micg6JgdvL7Vr7poHN1d6+G871fc=,iv:GXQ0d8RlG4B0AI0th/LUXiwkIE9wTjsU5g7flb0tfsw=,tag:mPSREZx5W24sbbQt4e66qg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:pzehrotldtZKz/T0cuMd3iMbbErjg0UlOL83Cro31rUJUtVglkxsiVzG2FQ=,iv:pTT5mGisNUn5QMCeW42UeccnVjwCwjssUfkpGH0o8gs=,tag:57GGzYQEf6vXDwBIIBoJEw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:u/IYCExQjK3zjyZpNiHsRrzvBXo0H0DpzopEa83iNVuGWjSHVJs3oDdd8JmdNFs=,iv:X9oWSokJDfn0ND6wfCBe4fkwnOzG6UI66GmDNfqA1FM=,tag:jvp4vpP637ZFBjYDubqdoQ==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:41SQ1C2B7/GmcA==,iv:ipIkf/JDEq7nfE5fTh8CchEcEwgabJQbDTmxXtG5rJ0=,tag:9nG4zj0buvu9Hn5O5zrE2g==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:6CMfiiI=,iv:tk5jlpC+09Jp5ZMZLuxBZ9Zcbslj8uVO9rkec1NnCsk=,tag:L3ppYDz3vm5rl1mWxOkewA==,type:str]
    WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:AFQLvjMhGzpJKWuW6To=,iv:TAhsApZ4uRPlK5WI6dKxm0T9oK2HrmxzR2fCNdbCLFg=,tag:AZoIWoEp7zenIz3wOa9FyA==,type:str]
    FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: ENC[AES256_GCM,data:UC9k,iv:KFW/W26WryudLMKloyYzYFbG1+SFCMNvKdTLiyAZeXk=,tag:kVztYDiSoeZXU91dH/H6Kg==,type:str]
    FIREWALL_DEBUG: ENC[AES256_GCM,data:TrGEAw==,iv:0AkomPKotOerjCJTmwOzidFbCqmSQMVsld84ApOnMJY=,tag:mpJ04UIU1jjB7+X4+8RfNQ==,type:str]
    HTTP_CONTROL_SERVER_ADDRESS: ENC[AES256_GCM,data:gUldejxLYrbFYw==,iv:bXm9G0L6eb+mhEH0Epzca+6ghGYe1tndMoB9drsS8JI=,tag:VLuerNM1SeZBaFBv6RVMqg==,type:str]
    HTTP_CONTROL_SERVER_LOG: ENC[AES256_GCM,data:jf+H,iv:JMQh43xUWzh1swXdTUOIoO84wQDMlGH+i7ZIH/ihzPQ=,tag:I88kMoCKrZjlmDDltXzBnA==,type:str]
    HTTP_CONTROL_SERVER_USER: ENC[AES256_GCM,data:VvvPaTcvSHb+Ww==,iv:LwKRtnylTsVJ9iRA/jjaL9/gtG6DTrJqS2Off0jeWno=,tag:G+xUtGu5fG50QP2qQEkMiQ==,type:str]
    HTTP_CONTROL_SERVER_PASSWORD: ENC[AES256_GCM,data:VDO4sMPSCWXjtAQGt+J27YOtZC/tEA==,iv:WIWInJS3K0UYTY8OZZX1UegL/WEA4o9HW061QU8GMIY=,tag:42bzJeZu8IsJC/613dmojw==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T22:22:35Z"
    mac: ENC[AES256_GCM,data:uhyhXx2PN8UvDwI1dvwOHgTm97zuOSSR+yUa4QRxIky2xFG7bWi0466J/iRoK0muCpxtKL3bgKvqYMAnScyXaFiHi5kRYVwfkvPr+KfuLQgPwIBwFRueo+yevKPpZMRhCJuaCLeBHd/1HF5WsXc2h+ivjdIg5VmIYP2eJYHpoeI=,iv:xJJgnFigA54F08mtC7NoMlxYc3/B9rMT5AtKJBTynpc=,tag:tMI8mq2YMWGhqw3NO60wew==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: vpn-gateway
stringData:
    config.toml: ENC[AES256_GCM,data:+mU1yJdlbpkpTfiVfPc=,iv:DpVd2eqEKV+LVksKBw4fuTgDnIy7ieHAEhmNt6eHOFU=,tag:r0xwaBCc3VUUdk336nxp+w==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T22:22:35Z"
    mac: ENC[AES256_GCM,data:uhyhXx2PN8UvDwI1dvwOHgTm97zuOSSR+yUa4QRxIky2xFG7bWi0466J/iRoK0muCpxtKL3bgKvqYMAnScyXaFiHi5kRYVwfkvPr+KfuLQgPwIBwFRueo+yevKPpZMRhCJuaCLeBHd/1HF5WsXc2h+ivjdIg5VmIYP2eJYHpoeI=,iv:xJJgnFigA54F08mtC7NoMlxYc3/B9rMT5AtKJBTynpc=,tag:tMI8mq2YMWGhqw3NO60wew==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-auth
    namespace: vpn-gateway
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:fm0GFp1zoYod5m3f7ULCwk+aCCWzRw==,iv:ueom+x776KeNwQP5TO8ZjKj69ipOEV/Xrz0mHo3ZSss=,tag:j6P5YYBfsRqADdvAqiO5Tg==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T22:22:35Z"
    mac: ENC[AES256_GCM,data:uhyhXx2PN8UvDwI1dvwOHgTm97zuOSSR+yUa4QRxIky2xFG7bWi0466J/iRoK0muCpxtKL3bgKvqYMAnScyXaFiHi5kRYVwfkvPr+KfuLQgPwIBwFRueo+yevKPpZMRhCJuaCLeBHd/1HF5WsXc2h+ivjdIg5VmIYP2eJYHpoeI=,iv:xJJgnFigA54F08mtC7NoMlxYc3/B9rMT5AtKJBTynpc=,tag:tMI8mq2YMWGhqw3NO60wew==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
