apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-config
    namespace: vpn-gateway
stringData:
    TZ: ENC[AES256_GCM,data:SpPI6u1i30jX2Vz8VQ==,iv:dwS/PAICIL9qDjfKakrYv/rYD0v3GdfOFzyQYSIuBmA=,tag:dODfZoCl+/UCL+ImTXtfvw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data://C3bM2WKw==,iv:4MJwSIDReRmn8x8YYOGk0CHO8pb7zydw5j73+tCJMF4=,tag:DIvPNmfiU4v8LifmSc7hrg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:sc/CwRKO,iv:nwhhAFQS2596pkHgR9dh2DEPkTYz2RHH+LZCMj5/V44=,tag:Mdx6MGgyMNxl37PclSbcNQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:GDKYR1JpsS1689lxTJRpB+v1E6CJEs2micg6JgdvL7Vr7poHN1d6+G871fc=,iv:GXQ0d8RlG4B0AI0th/LUXiwkIE9wTjsU5g7flb0tfsw=,tag:mPSREZx5W24sbbQt4e66qg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:pzehrotldtZKz/T0cuMd3iMbbErjg0UlOL83Cro31rUJUtVglkxsiVzG2FQ=,iv:pTT5mGisNUn5QMCeW42UeccnVjwCwjssUfkpGH0o8gs=,tag:57GGzYQEf6vXDwBIIBoJEw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:u/IYCExQjK3zjyZpNiHsRrzvBXo0H0DpzopEa83iNVuGWjSHVJs3oDdd8JmdNFs=,iv:X9oWSokJDfn0ND6wfCBe4fkwnOzG6UI66GmDNfqA1FM=,tag:jvp4vpP637ZFBjYDubqdoQ==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:41SQ1C2B7/GmcA==,iv:ipIkf/JDEq7nfE5fTh8CchEcEwgabJQbDTmxXtG5rJ0=,tag:9nG4zj0buvu9Hn5O5zrE2g==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:6CMfiiI=,iv:tk5jlpC+09Jp5ZMZLuxBZ9Zcbslj8uVO9rkec1NnCsk=,tag:L3ppYDz3vm5rl1mWxOkewA==,type:str]
    WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:AFQLvjMhGzpJKWuW6To=,iv:TAhsApZ4uRPlK5WI6dKxm0T9oK2HrmxzR2fCNdbCLFg=,tag:AZoIWoEp7zenIz3wOa9FyA==,type:str]
    FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: ENC[AES256_GCM,data:UC9k,iv:KFW/W26WryudLMKloyYzYFbG1+SFCMNvKdTLiyAZeXk=,tag:kVztYDiSoeZXU91dH/H6Kg==,type:str]
    FIREWALL_DEBUG: ENC[AES256_GCM,data:TrGEAw==,iv:0AkomPKotOerjCJTmwOzidFbCqmSQMVsld84ApOnMJY=,tag:mpJ04UIU1jjB7+X4+8RfNQ==,type:str]
    HTTP_CONTROL_SERVER_ADDRESS: ENC[AES256_GCM,data:1A27,iv:E1aB5FCQTPvpiiXiZSbYgXBtMJ9rFN3fUIOdV+yOzbI=,tag:dZAH8CSBVWhcHRL8beIQSw==,type:str]
    HTTP_CONTROL_SERVER_LOG: ENC[AES256_GCM,data:wdz5,iv:DQFwq5K2YgGg0zzARO9BZjSYVtz9MPSgUGenSgf8zhM=,tag:iWBfUlBxhj9f5zT2d9nfhA==,type:str]
    HTTP_CONTROL_SERVER_USER: ENC[AES256_GCM,data:VvvPaTcvSHb+Ww==,iv:LwKRtnylTsVJ9iRA/jjaL9/gtG6DTrJqS2Off0jeWno=,tag:G+xUtGu5fG50QP2qQEkMiQ==,type:str]
    HTTP_CONTROL_SERVER_PASSWORD: ENC[AES256_GCM,data:VDO4sMPSCWXjtAQGt+J27YOtZC/tEA==,iv:WIWInJS3K0UYTY8OZZX1UegL/WEA4o9HW061QU8GMIY=,tag:42bzJeZu8IsJC/613dmojw==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T23:14:30Z"
    mac: ENC[AES256_GCM,data:GbCEhQN+xG6PN7E7y7M4+1zw8+X+hIyzhV7JG7kIDiTktmkehhlZaznT3sCHHyAROcjSSHXx3duDDKcwIgmD7ETmbZFJieQxPWDsQCHbm3FXLHRmlL0ZoXziob508gxa024tiOk46MDc+3/dpsOhVhJqcVobsQFqsJ+dLBlki8M=,iv:LM16y98NEaJwVRWf8jQehKfCoPCaRAktrPZvY0GarxU=,tag:8RRoudAz3QpQmWJQxRDi6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: vpn-gateway
stringData:
    config.toml: ENC[AES256_GCM,data:dFx2KySRBGb9c9zcKqsCr9v7kn+VrqXXIR+w7kuArHmOtZUg+L/fuYdTzot0L9tcdQo6QGzEU6DG1tE8sWvRrYyxzT9iBXR2nqhqgZ/2r0trR+oN0RA5COTsundVhPcBhWMpUSYLqB9MnykrWvZviw2eW/qDYu7o1e9jPYFCVG9UU4J2NVEjj9UwKa4jGiDj6C4n+sGqLmKh4ZDs6vD0PuF8Wc3xm/F8AKDI4fvn7/l3N3PnJmzlpIBkvNSriPVw85Gz9X1XR19wkB2vUpjGlQUquIy8OFwqa+rCwnx4mEx1xchPBBtWhyVnu7BUpnLV0jEpqajkJgmZ/mjT,iv:2ZPfxVEA7B45qUxRdYYwLyXB3IrPSmbpxpPzzoYNoLE=,tag:Cgde8uXABVNGLKKUh05zJA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T23:14:30Z"
    mac: ENC[AES256_GCM,data:GbCEhQN+xG6PN7E7y7M4+1zw8+X+hIyzhV7JG7kIDiTktmkehhlZaznT3sCHHyAROcjSSHXx3duDDKcwIgmD7ETmbZFJieQxPWDsQCHbm3FXLHRmlL0ZoXziob508gxa024tiOk46MDc+3/dpsOhVhJqcVobsQFqsJ+dLBlki8M=,iv:LM16y98NEaJwVRWf8jQehKfCoPCaRAktrPZvY0GarxU=,tag:8RRoudAz3QpQmWJQxRDi6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-auth
    namespace: vpn-gateway
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:fm0GFp1zoYod5m3f7ULCwk+aCCWzRw==,iv:ueom+x776KeNwQP5TO8ZjKj69ipOEV/Xrz0mHo3ZSss=,tag:j6P5YYBfsRqADdvAqiO5Tg==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T23:14:30Z"
    mac: ENC[AES256_GCM,data:GbCEhQN+xG6PN7E7y7M4+1zw8+X+hIyzhV7JG7kIDiTktmkehhlZaznT3sCHHyAROcjSSHXx3duDDKcwIgmD7ETmbZFJieQxPWDsQCHbm3FXLHRmlL0ZoXziob508gxa024tiOk46MDc+3/dpsOhVhJqcVobsQFqsJ+dLBlki8M=,iv:LM16y98NEaJwVRWf8jQehKfCoPCaRAktrPZvY0GarxU=,tag:8RRoudAz3QpQmWJQxRDi6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
