apiVersion: v1
kind: Secret
metadata:
    name: samba-1
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:anc2Ep1Ro9xXJCbded7cp96BbgIf2SBpJuFpXUCHzXvuskU4QGoZbBEP+z2+19yQo5PK7jI4XzYZniEJktHTWVuIstGIhnpZsAZ2HaSlr+KabtPLrfAekNkmUAqWjXdan1pMK+mBx4Aje7MqC6hVG6O0cHgTFhNgYS6jspqm9V1X5zNSCHy6RihqpaEGVPJwCzzr6sJb+bGzNREZpTMYlpqns4L14QX+pQwEumqH237Ud0/RQTc6CLy3uhg8fX0LdYcfRimUmzwERdXbgN7tyKCYcZOqBnmlX+3qXkgV393WsGFNAPYiNqMFgdmAJUx4umgHd7o38ga6XhGXQ8npOa0GJ6uN1nt90rc1sbyNxyHjd0PtyHBXwQKcbNEOLO+0MIsVPFweKKVZvQVVZNujOsHuk099Cy8rwoMP9GRICdxWFcjLfJOCDZUipBEN9oZgBNgnj7eSffSVoTHWZisbhaN0DP0YxUQHrozbe+mXdWbo16T7Ny6XFCcbJFiuhsRDU21Cjt4KtULl2Q3hEOCPOw21ShQSlOKBofjSdOq1ea6F8LkMw+U8Cf4D/TSp4iLKiEBvfUOd+3hNTF+D3hGPs11bfn6BwX4j+p2uCKhjqiq1rzxVqozHvZscchCS5iqXe/qH9Ps5H/5wDsCN4ugP5pTrWbEZFYZdNcRkK4vj8oQXOzosugWIOeO9oHaYHKBXZNH7kYg=,iv:ism4tpK3p2Xipmp6BmcvTJWqTr/Sw2Ef9W2u/JnM44M=,tag:lxnRSlAGOMgL5h4odmSQBQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T21:47:34Z"
    mac: ENC[AES256_GCM,data:WXvWN9f6AMGBe0Uh7ER6RJAgpGglU59ezjUzv30f4Idw2JUISyI1r53cXT6ptFjaRq9byysJO9OXsaDSoHa7WAwhmTq15KuXTpqGOPtS3h7XKO5Q+eTxhH34Xhjt0XBajuEpB+3RV/fmAhBTg0Q608fnGHnvoZc77nae449s1fE=,iv:V3ZJG8JWY+fszR+AQLya8La0k8XUaJ8Gw5wS3IiFQ/g=,tag:k4hyJeRKshmjeNemqu0b4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
