# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: kopiur-repository-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: cephiro/kopiur
        property: KOPIA_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: cephiro/kopiur
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: cephiro/kopiur
        property: AWS_SECRET_ACCESS_KEY
