apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: media
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["curl", "https://ifconfig.me"]

