apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: komga-dst
  resources:
    requests:
      storage: 2Gi
  storageClassName: linbit-local
