apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: network
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: pod-gateway
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: network

  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.13.0@sha256:a5b032e15f7570493977b330a5a86dcffebb807d35685ad803e47afb62d105f2

    service:
      vpn:
        enabled: true
        type: LoadBalancer
        ports:
          gluetun:
            enabled: true
            port: 80

    addons:
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: HTTP_CONTROL_SERVER_ADDRESS
            value: ":80"
          - name: HTTP_CONTROL_SERVER_LOG
            value: "off"
          - name: PUBLICIP_API
            value: ip2location
          - name: VPN_ENDPOINT_IP_VERSION
            value: "v4"
        envFrom:
          - secretRef:
              name: vpn-gateway-config
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            memory: 128Mi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        probes:
          liveness:
            enabled: true
            custom: true
            type: custom
            spec:
              exec:
                command:
                  - sh
                  - -c
                  - COUNTRY=$(curl -s https://ipinfo.io/country); echo $COUNTRY; if [ "$COUNTRY" = "BE" ]; then exit 0; else exit 1; fi
              initialDelaySeconds: 30
              periodSeconds: 60
              failureThreshold: 5
              timeoutSeconds: 5
        persistence:
          config:
            enabled: true
            type: secret
            name: gluetun
            globalMounts:
              - path: /gluetun/auth/config.toml
                subPath: config.toml
                readOnly: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: vpn-gateway-pod-gateway
      secret.reloader.stakater.com/reload: vpn-gateway-config

    routed_namespaces:
      - downloads

    settings:
      VPN_INTERFACE: wg0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.99.0/24"

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.12.0@sha256:6f6ab596afd5fef0ca4648eadfb21cd37ba86fa5afa8b85edcc072976a61fbed