---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app suwayomi
spec:
  chartRef:
    kind: OCIRepository
    name: suwayomi
  interval: 1h

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    controllers:
      suwayomi:
        pod:
          nodeSelector:
            kubernetes.io/hostname: fuu-01

        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.1.2087@sha256:de77d00edd3df9d064151b7ff0302805f744f66ec9147c3f0552ee7012712ba4
            env:
              TZ: Europe/Paris
              BIND_PORT: &port 4567
              WEB_UI_CHANNEL: "preview"
              AUTO_DOWNLOAD_CHAPTERS: true
              UPDATE_EXCLUDE_UNREAD: "false"
              UPDATE_EXCLUDE_STARTED: "false"
              UPDATE_EXCLUDE_COMPLETED: "false"
              DOWNLOAD_AS_CBZ: "true"
              EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
            envFrom:
              - secretRef:
                  name: suwayomi-config
            resources:
              requests:
                memory: 250Mi
                cpu: 500m
              limits:
                memory: 1500Mi

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Books
          gethomepage.dev/name: Suwayomi
          gethomepage.dev/icon: https://raw.githubusercontent.com/Suwayomi/Suwayomi-Server/master/server/src/main/resources/icon/faviconlogo.png
          gethomepage.dev/description: Manga Web Reader/Downloader
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - port: *port
                name: *app

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: *app
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk

      nfs-data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-pictures
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk/downloads
            subPath: downloads
          - path: /home/suwayomi/.local/share/Tachidesk/local
            subPath: local

      tmpfs:
        enabled: true
        type: emptyDir