apiVersion: v1
kind: Secret
metadata:
    name: suwayomi-config
    namespace: downloads
stringData:
    DATABASE_TYPE: ENC[AES256_GCM,data:8M0Bx+KNCuE3bA==,iv:FYnYDgO5XE12FiUJOh/SY8HGsNweNizM7b4ysPYd16U=,tag:yGtmqkn1TLz1l6um0zPgWA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:0yNB/4fn+a2DH3iPGzjLj1fv5DBUClxLFa7tTlXL3Z1cSLwJyq8KxwTcsxOWUjR+EbFjqdD4hbWikLOgvi80t9fmpWql2kZ2g/I9aIw1IP4=,iv:yE48OzJCNEHl2ZzrXqdyaD1Y0UCdn2GA5DA8tw3d5fM=,tag:Np+hquGOZVvqzoNnldR8tA==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:UqwrWnn3AJA=,iv:sQzBt/lU4v0ryZGEu+XXiPpYY5wtIPCXqdK8ya9KBMc=,tag:1abPxbGv3aWpSBNT548SoA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:MrEoyllhc2LHTqMIqCdRc7HLdAk=,iv:gKKaWC8ubbECyiYgO9JnYlcj+hBW+ed4MlqmoKLFxsA=,tag:KcG888HwMfb0dVH7yvlKGA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:29:10Z"
    mac: ENC[AES256_GCM,data:nMMhna2HtmyfvryZGYEuEsDbYNunw1akOupi2Sxv0yyn0h6ZeBvyo3Jato11fvhRKS2sI3z+2V5nOg/W+n3X0QrxU/UX6w0fyQMN/TxaAxkM81FUSKgSaplJN0jt4SsswmUTujNvJrc+F4zxRvS2bSqcgdC1MIio2xlFgMNt3p8=,iv:EhEW3H/uKesI4GXLXhpPMWspaxJgI3b2VhUJdcYxPAM=,tag:vmcne0O/9sTOGocIL5WWTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
