apiVersion: v1
kind: Secret
metadata:
    name: suwayomi-config
    namespace: downloads
stringData:
    DATABASE_TYPE: ENC[AES256_GCM,data:8M0Bx+KNCuE3bA==,iv:FYnYDgO5XE12FiUJOh/SY8HGsNweNizM7b4ysPYd16U=,tag:yGtmqkn1TLz1l6um0zPgWA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:0yNB/4fn+a2DH3iPGzjLj1fv5DBUClxLFa7tTlXL3Z1cSLwJyq8KxwTcsxOWUjR+EbFjqdD4hbWikLOgvi80t9fmpWql2kZ2g/I9aIw1IP4=,iv:yE48OzJCNEHl2ZzrXqdyaD1Y0UCdn2GA5DA8tw3d5fM=,tag:Np+hquGOZVvqzoNnldR8tA==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:UqwrWnn3AJA=,iv:sQzBt/lU4v0ryZGEu+XXiPpYY5wtIPCXqdK8ya9KBMc=,tag:1abPxbGv3aWpSBNT548SoA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:WFypihBxVTl25WoIPmtmFg9/XNfKNsu/,iv:o+yP2DcvA0ojnPjlOaNim3oQujFg4PhNx+TjlB4mvbU=,tag:u6bZXg8wK71LMek/SoVddg==,type:str]
    AUTO_DOWNLOAD_CHAPTERS: ENC[AES256_GCM,data:Rakmzlg=,iv:x0HHl68HP0us9Qw8pFTBxzdttw0Qxj9fJRU4JRGiCSQ=,tag:S1SZyHOG6nzDQBjkqvJ23g==,type:str]
    UPDATE_EXCLUDE_UNREAD: ENC[AES256_GCM,data:3fR708c=,iv:m34KZ6B94U/hsXibpsRRlSm9iQBb6T3iP7n0n6J7Jww=,tag:e+VPULxJGPeWOalqmb9jcQ==,type:str]
    UPDATE_EXCLUDE_STARTED: ENC[AES256_GCM,data:prNd7N4=,iv:dvetdLch0+adSn41GGzdzEiDZiDX4lAeAtnKnziGTCk=,tag:4yQAQDzVg6nZWxUyoPM/ig==,type:str]
    UPDATE_EXCLUDE_COMPLETED: ENC[AES256_GCM,data:OLN2dkY=,iv:DAHqL4PE15MT2i28LLC10dm3zbBjCfQSmYelTv7hSXA=,tag:YI7ndU2VattP9kT0q+hQHQ==,type:str]
    MAX_SOURCES_IN_PARALLEL: ENC[AES256_GCM,data:Hw==,iv:GGOr1A6TmLCcK8LSareTsK92s1MT5xaCjyfzUtcFSGQ=,tag:crXpXRgIIBa+iqKMF0equA==,type:str]
    UPDATE_INTERVAL: ENC[AES256_GCM,data:bQ==,iv:f6GCrccFCnhh6v8xb91e/0z3iR/z69P756SBNXs7ogk=,tag:tddYQZGdFFRQHv/noiptaA==,type:str]
    DOWNLOAD_AS_CBZ: ENC[AES256_GCM,data:PBGeuQ==,iv:nvcM+UFmD+nhAVHxUXAaz9PVNrImAN0jZXABtkezbho=,tag:0IxuFtsJwFK8iCDA5uNGLw==,type:str]
    TZ: ENC[AES256_GCM,data:eHY1x1VeT4ZUfh00lA==,iv:VKrrCwwcN9NnEPZw1pzhzOl8l6vnW2a8oZwCGyF7ej8=,tag:mV0Lk7er8zY9sD1/6zQVCA==,type:str]
    EXTENSION_REPOS: ENC[AES256_GCM,data:0sZT1lR/7ItCdc09Tcv5TRfBzSweagW7qC1Fz9ijHRsZ0S4dx1VaInWXX5d/eIrAbJ59WCarQGf1suknE8jMRxNlrHOblEYLrSoSD4HZ,iv:Py+6wllczlziq2WMCsvRuKGA37UJyd05svRF0U7j41Y=,tag:yVgpNHy1D7+kxdp9TdPxvg==,type:str]
    DOWNLOAD_CONVERSIONS: ENC[AES256_GCM,data:VZnq5eWqGg9RMuOITT1UTJ7ulkPNMtrfmnYa95BsBdNX0r6R4VtvUdGZKisgepjvCDxBwXC7GTMUBWinHNhBeSg03s8qRfgfw2/dP8k+W1FZjjGQfa5ZHlMEgvALkS34LwJ4jToogb1qw8yctcHKNGXc5Kz8CG2lW2Fj9xyiEOyuppEPcMSPmUeKzQrQw0Jry4ApDHjNMEXsNb+LbYeW/rrK7k82bQHbRMSZzg423AoQ9uwst+ANvVcyb6tf6JB+t+m7GPvBVZnpjw==,iv:wLYfjSzYY4slo0cSLUVSAzkIDvGD5+sNePqj+Sg42q0=,tag:cNHBAMJ1x9d5Qlx0S3BPTQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:29:15Z"
    mac: ENC[AES256_GCM,data:s/2d4nwqQiKCQexb46LdAGNejzakcpBsz0lZwJV78pAHUeQg27kmgFLF6SdkdpC6OKLLkPTrPpMRMZorPhqxdqvsLK8Q7a78jnQ4+9Ov3b+2MEjNLBk2QFJixD8/wXUwy4lQDlr46UH8jngav2MIoooypdqBL8q7IA69HpzsvDQ=,iv:YnIZFEFAUJKB8KNFlcD3/YJHKWtvTrEt/0o07WDJV7w=,tag:XF9qSjc3bX2jEo9APTf4zA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: suwayomi-image
    namespace: downloads
stringData:
    TZ: ENC[AES256_GCM,data:eHY1x1VeT4ZUfh00lA==,iv:VKrrCwwcN9NnEPZw1pzhzOl8l6vnW2a8oZwCGyF7ej8=,tag:mV0Lk7er8zY9sD1/6zQVCA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:29:15Z"
    mac: ENC[AES256_GCM,data:s/2d4nwqQiKCQexb46LdAGNejzakcpBsz0lZwJV78pAHUeQg27kmgFLF6SdkdpC6OKLLkPTrPpMRMZorPhqxdqvsLK8Q7a78jnQ4+9Ov3b+2MEjNLBk2QFJixD8/wXUwy4lQDlr46UH8jngav2MIoooypdqBL8q7IA69HpzsvDQ=,iv:YnIZFEFAUJKB8KNFlcD3/YJHKWtvTrEt/0o07WDJV7w=,tag:XF9qSjc3bX2jEo9APTf4zA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
