apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-s3-creds
    namespace: database
stringData:
    samba.yaml: ENC[AES256_GCM,data:mQ8la4/0fzPSgsKEXkzipc5e+GjLt41WyL6b7w3L73nsfjxjy1wR6b37NNnV5l+D8OnE1yG1BjXDkmyrmfyoyZt797yy+WuaEJjIeZc4wONw9z9CMV6H6EJRjUJvATFiHiE5f/SRne7/kawGC617OTBj1T39tlTGVSZIAE+LgR6P8jf4ZqFDVZF39pcvtqc=,iv:vBgcJ99G2xC8HcrtmhP5dc+6d2GAuDK+WQK4j49ijFw=,tag:wqapWgl0cn9Teo9ypw/2GQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:20:02Z"
    mac: ENC[AES256_GCM,data:vImg640izkgUyGWf3atH9ASB4bcXU3KidExQlCngV7dRYsmkZ7zLQsZ9DvfbXJE1yPPoglWjGm9CMlh6POI8Z+4xBFBGTfoxc/zKWmnIA2pJ/tt3pC/VwrHKxqQzinO65X+6Ez0aHo7zYYobGrIgW48N2qnp4NxUrxqBVDnDKTo=,iv:/cWnkHd++rBcHVZr1Wag940P7Dx1ZIqzcAdaNMxRLOY=,tag:i4SxfyEngs8gVuIw51+kjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
