apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-s3-creds
    namespace: database
stringData:
    s3.conf: ENC[AES256_GCM,data:EjGl/2uqCCScXvbOb1g/pTxFYr9gmfkKjA7oefgUu3CDwkFSKvjgb7xx0QYjJ3uVVgN7T4oQT47ZR5xUmM3cXzywyEWvENKyve4OIRufHF2l4CBAs2ICliZwyHuSj1KDDuJMF7e5uaiLxOllq+Ld8xWMgr3yuyFEWER6Gob6hoD8IFHTNtaCnw==,iv:H38JnDn+DRehrvr8DZx2JyktYRlkVdPAZDReyg/FSt0=,tag:PadW6bNmt75wp/7U39ch0w==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:20:49Z"
    mac: ENC[AES256_GCM,data:Xjqp0X7lvaLXZgGGwMcf8ReUR5ElMgxEPS7q44h3Eh6KZyf3IyiTsnpQAjSRi6QiRFQa2dfpfck5HxhOEaHG1F41tA7qam0flzlMmZcKoo6Piiq6y/+srM0lpi2pcSRZDIgQJensPmpqvHQFTgVP+/x2H1r4bVFAX2E92Az0xYE=,iv:lCm6fz2EDQAVoe38Uj7uth09zmOa7SoVfDe/3DiBrWc=,tag:1YCAZVHOLcdKp8abxpbrHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
