apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-s3-creds
    namespace: database
stringData:
    s3.conf: ENC[AES256_GCM,data:Z2Id2oq4XhqdneXFbOjSK5Ml0pTmMO8sEypNr3bCN3f5m4Nfn7aHX41XJWYQuEh2cQ9TCSV8zJKLqx44rog/YhIPV47XcneBSGMOlgAM/wB4AWHqmhSKqmGZO+g+qHKjcQ6ObtudEycTgCwE9aH6qhqG6fLAA0Gq/FpRMOWmYmf0K06TYXg=,iv:xpL5/O9+ibwUFqC5/6otdQC6q2dPXfCpx0xrJlr1Jmg=,tag:OziP+BHt+X7g6JuI79TXhg==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:27:45Z"
    mac: ENC[AES256_GCM,data:Aff+3Byut8yYndWcEbmu8BK9myg+6otTs6ab141WTza6ARB6bNfvv7CTHnAuQF/kvcgb/PuO6JccoZp9LdYF0vkwflVJwpmQb7ndNQaBVihn+IfVpuf1gM0hsnGP1D1DLur/YvYgPQ5wRF85CDKxN33kaUT/roDcMrd4M0piutY=,iv:26OFSKC82DEkxW9JG2cP2jjsDVnI2dYMP//WtwLvv/s=,tag:nh9hQd5tqctcgpqKGVJ3hA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
