---
# This policy redirect traffic to the egress node for pods that have the label use-vpn: "true"
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: vpn-egress-policy
spec:
  selectors:
    - podSelector:
        matchLabels:
          use-vpn: "true"
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: downloads

  destinationCIDRs:
    - "0.0.0.0/0"
    - "::/0"

  excludedCIDRs:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "10.42.0.0/16"
    - "10.43.0.0/16"

  egressGateway:
    nodeSelector:
     matchLabels:
      egress-gateway: "true"
---
# This policy allows inbound connections to the vpn-gateway on port 8000 to gluetun http_control_server
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vpn-gateway-control-server
  namespace: vpn-gateway
spec:
  endpointSelector:
    matchLabels:
      app: gluetun-egress
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: vpn-lrp
  namespace: vpn-gateway
spec:
  redirectFrontend:
    serviceMatcher:
      namespace: vpn-gateway
      serviceName: vpn-forwarder

  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app: vpn-gateway
    toPorts:
      - ports:
          - port: "8000"
            protocol: TCP