apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-config
    namespace: vpn-gateway
stringData:
    TZ: ENC[AES256_GCM,data:SpPI6u1i30jX2Vz8VQ==,iv:dwS/PAICIL9qDjfKakrYv/rYD0v3GdfOFzyQYSIuBmA=,tag:dODfZoCl+/UCL+ImTXtfvw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data://C3bM2WKw==,iv:4MJwSIDReRmn8x8YYOGk0CHO8pb7zydw5j73+tCJMF4=,tag:DIvPNmfiU4v8LifmSc7hrg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:sc/CwRKO,iv:nwhhAFQS2596pkHgR9dh2DEPkTYz2RHH+LZCMj5/V44=,tag:Mdx6MGgyMNxl37PclSbcNQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:A4w6k4gLiDG7Xr7GeP9Sy+Jz+5xqUvE9j2wPZAFUfuspzAI4XFrzM37Ip0U=,iv:CcaAhfSN9vWXbQ50xJijNdSTIQ8hP3+t0uBheL2oUdk=,tag:87fKt3Rb4ZSzhw3V/lTQCQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:NOEgndB6W2DEWv2g25Fayc6AEX7HLsAyisIMs11b+DBsSez1jcE9AMsArIU=,iv:Txpk4Q8ecLKSE4WwHXo/ThvvkGXRrwjSCkWjClHa0Ms=,tag:siPS+5mIAq25t8bQiPz/QQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Ku7EOhudf1Yaz9gsSPiGBHfrTdfxWGp9cXvGEFJYt3mSEjE8oyHagwTmQ6Bf3ys=,iv:9MFcQStQF7r3XqzKBnTrd6U2l/MFQK7tOEcCzUPIfE0=,tag:WzbSo9+wpRbkT46Tr5c+UQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:JAD0baA=,iv:Zypr9UuoiuiiRyUq6DT1eePbmNfqfd56Gh29MBIMOd8=,tag:jL0qBqsQ+okyFMcWc4OYsg==,type:str]
    WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:OtTrHPtz76lbutRi+bw=,iv:iBX5n99B9WLgT6IRyjkCDz4Zx1uobfJCtB8HjgTV2Lo=,tag:QGow/3RkyjTIc0YHKCMgIA==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:6MmOqsOtSxvnfvVE7IiEUFGMlT/zHTkk4A==,iv:51AnRWJdZKPlmW4GZy9jRgpdwMZ+HBFhWAc8YRxb8c4=,tag:Q++3I5DR5GvnO+IduWfaow==,type:str]
    FIREWALL_DEBUG: ENC[AES256_GCM,data:TrGEAw==,iv:0AkomPKotOerjCJTmwOzidFbCqmSQMVsld84ApOnMJY=,tag:mpJ04UIU1jjB7+X4+8RfNQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T23:24:03Z"
    mac: ENC[AES256_GCM,data:yFglPbrsLmaY/adiroxauz7n0ZAwRx1BhVueG/TuGbYRxrJoDwf9aZwXra48cRwo0AfZLZ3D5bGi3lMJSf6GeCnC0EUgIkV1nbNAEQY6GX7UGc0BG1vfGfY9PxqZITP+gKY9LNKeJmp1lvQubZ+ez34w+ETj6TAfaFHDqOR4bXE=,iv:0tAGw6SW+0439oxkYAUR4GFeqoP0QxTQR8vt9ZaC69s=,tag:LJbCZ7wyFYFe74KwNeR/Mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: vpn-gateway
stringData:
    config.toml: ENC[AES256_GCM,data:6xi7rCVKUUAY977Aj5D5evRtMPTCiDiKZ2Cv0f6cCxk+Xcl62OWBW/s6WgXd5AY7CBSni+3c+0nUW3rvbpIvVpNbbOiVO3dMuKudXrPLhVq8KXLMYXUCiPQbI87IN+BKRns6iq00x0CqdEbcLhw=,iv:sz4vbPj9javcHhUu3dPpFH6WJrk/5FTCvru6HqHecE8=,tag:jOOb8te4KmL9QCdeWvUN3Q==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T23:24:03Z"
    mac: ENC[AES256_GCM,data:yFglPbrsLmaY/adiroxauz7n0ZAwRx1BhVueG/TuGbYRxrJoDwf9aZwXra48cRwo0AfZLZ3D5bGi3lMJSf6GeCnC0EUgIkV1nbNAEQY6GX7UGc0BG1vfGfY9PxqZITP+gKY9LNKeJmp1lvQubZ+ez34w+ETj6TAfaFHDqOR4bXE=,iv:0tAGw6SW+0439oxkYAUR4GFeqoP0QxTQR8vt9ZaC69s=,tag:LJbCZ7wyFYFe74KwNeR/Mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-auth
    namespace: vpn-gateway
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:gnHpTck+tfNyEwA0hK30s5lAPUTv9A==,iv:IZK8+/hrRpxlmCA2wwgRsDVV7lXAfy08eQtBwCGrMGg=,tag:UwbB05i26LuPxUA2TV9M+Q==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T23:24:03Z"
    mac: ENC[AES256_GCM,data:yFglPbrsLmaY/adiroxauz7n0ZAwRx1BhVueG/TuGbYRxrJoDwf9aZwXra48cRwo0AfZLZ3D5bGi3lMJSf6GeCnC0EUgIkV1nbNAEQY6GX7UGc0BG1vfGfY9PxqZITP+gKY9LNKeJmp1lvQubZ+ez34w+ETj6TAfaFHDqOR4bXE=,iv:0tAGw6SW+0439oxkYAUR4GFeqoP0QxTQR8vt9ZaC69s=,tag:LJbCZ7wyFYFe74KwNeR/Mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
