---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
  data:
      - secretKey: KOPIA_PASSWORD
        remoteRef:
          key: cephiro/kopia
          property: password
      - secretKey: KOPIA_REPOSITORY
        remoteRef:
          key: cephiro/kopia
          property: repository
