apiVersion: builtin
kind: PatchTransformer
metadata:
  name: generate-replicationsources
patch: |-
  - op: replace
    path: /metadata/name
    value: $(NAME)
  - op: replace
    path: /spec/sourcePVC
    value: $(PVC)
  - op: replace
    path: /spec/trigger/schedule
    value: $(SCHEDULE)
  - op: replace
    path: /spec/kopia/repository
    value: $(REPO)
  - op: replace
    path: /spec/kopia/copyMethod
    value: $(COPYMETHOD)
  - op: replace
    path: /spec/kopia/volumeSnapshotClassName
    value: $(SNAPSHOTCLASS)
  - op: replace
    path: /spec/kopia/accessModes/0
    value: $(ACCESSMODE)
target:
  kind: ReplicationSource
vars:
  - name: NAME
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.name}
  - name: NAME
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.name}
  - name: PVC
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.pvc}
  - name: PVC
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.pvc}
  - name: SCHEDULE
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.schedule}
  - name: SCHEDULE
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.schedule}
  - name: REPO
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.repo}
  - name: REPO
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.repo}
  - name: COPYMETHOD
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.copyMethod}
  - name: COPYMETHOD
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.copyMethod}
  - name: SNAPSHOTCLASS
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.snapshotClass}
  - name: SNAPSHOTCLASS
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.snapshotClass}
  - name: ACCESSMODE
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.accessMode}
  - name: ACCESSMODE
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.accessMode}
