apiVersion: builtin
kind: PatchTransformer
metadata:
  name: generate-replicationdestinations
patch: |-
  - op: replace
    path: /metadata/name
    value: $(NAME)-dst
  - op: replace
    path: /spec/kopia/repository
    value: $(REPO)
  - op: replace
    path: /spec/kopia/sourceIdentity/sourceName
    value: $(NAME)
  - op: replace
    path: /spec/kopia/copyMethod
    value: $(COPYMETHOD)
  - op: replace
    path: /spec/kopia/capacity
    value: $(CAPACITY)
  - op: replace
    path: /spec/kopia/storageClassName
    value: $(STORAGECLASS)
  - op: replace
    path: /spec/kopia/volumeSnapshotClassName
    value: $(SNAPSHOTCLASS)
  - op: replace
    path: /spec/kopia/accessModes/0
    value: $(ACCESSMODE)
  - op: replace
    path: /spec/kopia/moverVolumes/0/volumeSource/nfs/server
    value: $(NFSSERVER)
  - op: replace
    path: /spec/kopia/moverVolumes/0/volumeSource/nfs/path
    value: $(NFSPATH)
target:
  kind: ReplicationDestination
vars:
  - name: NAME
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.name}
  - name: NAME
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.name}
  - name: PVC
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.pvc}
  - name: PVC
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.pvc}
  - name: SCHEDULE
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.schedule}
  - name: SCHEDULE
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.schedule}
  - name: REPO
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.repo}
  - name: REPO
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.repo}
  - name: COPYMETHOD
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.copyMethod}
  - name: COPYMETHOD
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.copyMethod}
  - name: STORAGECLASS
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.storageClass}
  - name: STORAGECLASS
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.storageClass}
  - name: SNAPSHOTCLASS
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.snapshotClass}
  - name: SNAPSHOTCLASS
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.snapshotClass}
  - name: ACCESSMODE
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.accessMode}
  - name: ACCESSMODE
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.accessMode}
  - name: NFSSERVER
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.nfsServer}
  - name: NFSSERVER
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.nfsServer}
  - name: NFSPATH
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.nfsPath}
  - name: NFSPATH
    objref: {kind: ConfigMap, name: volsync-pvc-direct, apiVersion: v1}
    fieldref: {fieldpath: data.nfsPath}
