apiVersion: builtin
kind: PatchTransformer
metadata:
  name: generate-snapshot-pvcs
patch: |-
  - op: replace
    path: /metadata/name
    value: $(NAME)
  - op: replace
    path: /spec/resources/requests/storage
    value: $(CAPACITY)
  - op: replace
    path: /spec/dataSourceRef/name
    value: $(NAME)-dst
target:
  kind: PersistentVolumeClaim
  name: APP_NAME
vars:
  - name: NAME
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.name}
  - name: CAPACITY
    objref: {kind: ConfigMap, name: volsync-pvc-snapshot, apiVersion: v1}
    fieldref: {fieldpath: data.capacity}
