---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: volsync-pvc-snapshot
    files:
      - pvcs-snapshot.yaml

  - name: volsync-pvc-direct
    files:
      - pvcs-direct.yaml

transformers:
  - generate-sources.yaml
  - generate-destinations.yaml
  - generate-pvc-snapshot.yaml
