---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}
spec:
  accessModes:
    - ${VOLSYNC_ACCESSMODES}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${APP_NAME}-dst
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: ${VOLSYNC_STORAGECLASS}
