---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP_NAME}-dst"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes:
      - ${VOLSYNC_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CAPACITY:=5Gi}
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            server: 192.168.100.192
            path: /export/volysnc
    repository: ${APP_NAME}-volsync
    sourceIdentity:
      sourceName: ${APP_NAME}
    storageClassName: ${VOLSYNC_STORAGECLASS:=linbit-local}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=linbit-snapshot}