apiVersion: v1
kind: Secret
metadata:
    name: tranga-api
    namespace: downloads
stringData:
    DATABASE_TYPE: ENC[AES256_GCM,data:8M0Bx+KNCuE3bA==,iv:FYnYDgO5XE12FiUJOh/SY8HGsNweNizM7b4ysPYd16U=,tag:yGtmqkn1TLz1l6um0zPgWA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:OTPby2OEQlWbu89VYxCSahyMpy8Ti5wLRQ9G/4W3SqOIuCP3bkDzk/3mx70qAAQ2Ad62xmIiFC0NhA7vAqwOadVY/SdXOGEvGE214CQx,iv:9X5QMKMAw5q2JJv1SnO823aO+qL6644/ElBjMkGdoWk=,tag:xRk66m2oCtaH2h65XygI/w==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:V6eEQukg,iv:2NE1yt+NEhwWBerRkdAEyQucPTcbUy1LOL+IqfGX/Kc=,tag:tzdxbM7YrjdPwE7yMWsysQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:WFypihBxVTl25WoIPmtmFg9/XNfKNsu/,iv:o+yP2DcvA0ojnPjlOaNim3oQujFg4PhNx+TjlB4mvbU=,tag:u6bZXg8wK71LMek/SoVddg==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T20:39:34Z"
    mac: ENC[AES256_GCM,data:BFOjt/qMYrVJdLKako3lsEAEAchbUiORlWqsZRdfNdDopQypClc1e/ts40Qutt+ScnbUgCzk7niSedkqtj92fk4l9KdWgr4PMfwLlCgcoMm4EgqIBmfJHOFcmH10Zc1JM03YtYF4TF3q/LFulb7XcsTssqB+OHjwsmA9LcMzDKk=,iv:yYfEAmFRfqKoRQSTMIYA7R7y83QFp9sICXNfEvkYF+Q=,tag:mCsPrkkWR6xiqsP7j9h4aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
