apiVersion: v1
kind: Secret
metadata:
    name: tranga-api
    namespace: downloads
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:RtPZdxz2RVOW+8al/49pAAjIDhBUqr2zfwCN5Odg+g0lwHuANNwmeEXl75ulyK270JgDqi5Zr+xkb5Z9R9JX3QmerxBBllnuJN73AYsb,iv:bVhfjH/rT53PNqZgDXOS0WlttdcveMo+TNYKIWLk6B4=,tag:tUDaGLZxFy81VRqCShEbQg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:vLW+hqfA,iv:wRZKvAqKxVe5P1HCpY/lUWpJ0gahoC1xBAXb3rLYCwQ=,tag:G41Rp3USVUGnukCPkjztKA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:aM9Edh47,iv:lYjWcTmq6fu+BiTu4UTx5ZF7LyG/hbq7We00AxIZvGI=,tag:y+bD7/Og2o84vYQL763T3A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rqATxjcDzZXqjcQUenhXcxgD3DA0gwzF,iv:wm0uzDcSqx4dUIoLIweUdd5VvPl4rHDZ32rIJy3cYhY=,tag:qgdwm58oiHkFnFV9V39p8g==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:32:18Z"
    mac: ENC[AES256_GCM,data:T6ID3/a8d7TqAeIKwqzxSaLOxZCTb+wICraPSphieHYAIt1FvG+AOO0harkDFEES9+VkvpjMd08rC/DTPzgyCSKeyBpAhT/ZMlL/vLepQ6Y6eSb/5ZFJyTGkHDeLTPrU8R2Nsia5S3/Q+WVg4bvjvrHlyqUKqN+RET8DqsTj4Ug=,iv:mWvIEDf1/KnEp1f0QQOEmMWTMqVYUh23q6Fg2eb3MkY=,tag:OY1h2FncIw8gSfJ5yjNhrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
