apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: database-credentials
spec:
    refreshInterval: 5m
    secretStoreRef:
        name: vault-backend
        kind: ClusterSecretStore
    target:
        name: database-credentials
        creationPolicy: Owner
    data:
        - secretKey: ENC[AES256_GCM,data:6X3jFQZHQbA46pbQlw==,iv:ga2RL6vMKPN9lfuKR5ukk1beGWlQSpM7e1Yct5nyxqY=,tag:PP7m3d7I/8OZd159ctoOIw==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:fxVcB+KsAETp3CGg9va0mA==,iv:8wDc5PW0gHxZzAk/4RYCC7BMyMRtYfs03OA39Q7EuCo=,tag:3fTTT1tHXZMDI4bmIWCGdw==,type:str]
            property: ENC[AES256_GCM,data:kVBmTA==,iv:5QM841RjbgFpssGUkGX4zAFxZQ3DFqmwu7SjH32B/Io=,tag:sPu2DWZSweK2Xb9xurIOYA==,type:str]
        - secretKey: ENC[AES256_GCM,data:o7adGQ95ylv+UV4=,iv:6BH+5Kxu0PODgprRB2HSQVGmXAkfjXGmHSUf899cpDg=,tag:Tpw1PP4jYY7SV5hDLXU1bg==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:fxVcB+KsAETp3CGg9va0mA==,iv:8wDc5PW0gHxZzAk/4RYCC7BMyMRtYfs03OA39Q7EuCo=,tag:3fTTT1tHXZMDI4bmIWCGdw==,type:str]
            property: ENC[AES256_GCM,data:7eIZZmI2,iv:s7yat36rY2+9r7JUI0RlWBREopCv6o/mqGkdCfGl2t4=,tag:VSP2XzD/CtvHxUOwA3x8Ew==,type:str]
        - secretKey: ENC[AES256_GCM,data:xDKNHldFS0B5pr7rrw==,iv:ZPjK+JrKTcLH77Ex9FOUCJ+N3KDiL0KIBoY9lVmzqf4=,tag:aomX9MAe4MLV4J7aAtmclA==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:fxVcB+KsAETp3CGg9va0mA==,iv:8wDc5PW0gHxZzAk/4RYCC7BMyMRtYfs03OA39Q7EuCo=,tag:3fTTT1tHXZMDI4bmIWCGdw==,type:str]
            property: ENC[AES256_GCM,data:BH9PP7bIuk4=,iv:wPIytIfsIi8Q5uVpeT0TbImYAQMIZdvUHIlH3lTIlo4=,tag:eiXzrhE6MrWoYvLoaRK2Pg==,type:str]
        - secretKey: ENC[AES256_GCM,data:Sqsq77C/LQuXY7hvlZXPc6Q=,iv:tmh6wJO+iyCS8+go99BWELMUarPz3raXuhYXLRLBpJY=,tag:jxFh3nJhcg8TXO+5KOCAcA==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:fxVcB+KsAETp3CGg9va0mA==,iv:8wDc5PW0gHxZzAk/4RYCC7BMyMRtYfs03OA39Q7EuCo=,tag:3fTTT1tHXZMDI4bmIWCGdw==,type:str]
            property: ENC[AES256_GCM,data:knFNnbPLXm8=,iv:MpXfOf7qj7RALoYBE6hFYLtB+HYXWqjQGrbUjHDzo/Y=,tag:Neniuhe41ay4wCQaD1ESmA==,type:str]
        - secretKey: ENC[AES256_GCM,data:igmsClwv1mWmtEHGXLEEiA==,iv:oQb/NQ0uYh7cPRhkh93Xz+b1uKsYjqpLdEPjkO+5o2Y=,tag:qppiPWvcdnfLxjt0Fka1mg==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:6rlikT3VfRuU9bMNiXpngQ==,iv:MA5w4fqcxxl2TTxAOpnjC7pmD+nhJjeNsYvketE0V4A=,tag:Kj+AnXWlYDubbWzIlPLW3g==,type:str]
            property: ENC[AES256_GCM,data:HOO3V1lyDpoOLsfdiAMv3hA=,iv:gsIRl5iRKlo+BaQWjOFtKgeCfaUd+9XUwhVSKub4cXg=,tag:fCE9Edl0w7CA05XoP3+YcA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T09:57:46Z"
    mac: ENC[AES256_GCM,data:ZJMfUXmfnIx4MXuMa7X+UGLFPK8MT/tWO/IJitdkIm1LLqUmBrHfdtoXjDq7caRrxgXo3ECs0ztgRJnWtBYkPyD6J6ivwAWtJBdRHEzbgXQx+IhS3YD1OFAmf4CPmle5/ysAnqrTY+I/7y9Zh5sX+cRrNuo1alwSFZBRXWAdUuw=,iv:h8F38Lrlhmyt1jQPKEq64vufirZK9KriCt+mWVz3QIk=,tag:iCEjszcz8g8bbwyekCD78A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
