---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
  interval: 1h
  values:
    leaderElect: true
    serviceAccount:
      automountServiceAccountToken: true
    controller:
      serviceAccount:
        automountServiceAccountToken: true
    extraVolumes:
      - name: vault-token
        projected:
          sources:
            - serviceAccountToken:
                path: vault-token
                expirationSeconds: 600
    extraVolumeMounts:
      - name: vault-token
        mountPath: /var/run/secrets/tokens
        readOnly: true
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
    webhook:
      replicaCount: 2
