---
# yaml-language-server: $schema=https://raw.githubusercontent.com/piraeusdatastore/piraeus-operator/refs/heads/v2/config/crd/bases/piraeus.io_linstorsatelliteconfigurations.yaml
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: linstor-satellite-zone-b
spec:
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer
  nodeAffinity:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - b
  storagePools:
  - name: data-zone-b
    lvmThinPool:
      thinPool: data
    source:
      hostDevices:
      - /dev/sdb
  patches:
    - target:
        kind: DaemonSet
        name: linstor-satellite
      patch: |-
        - op: add
          path: /metadata/annotations/reloader.stakater.com~1auto
          value: "true"