---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: syncthing
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      syncthing:
        containers:
          app:
            image:
              repository: ghcr.io/syncthing/syncthing
              tag: 2.0.10
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 150M
              limits:
                memory: 300M
    service:
      app:
        controller: syncthing
        primary: true
        ports:
          http:
            port: 8384
      listen:
        controller: syncthing
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: sync.${SECRET_DOMAIN}
          lbipam.cilium.io/ips: 192.168.99.55
        externalTrafficPolicy: Local
        ports:
          listen:
            port: 22000
            protocol: TCP
            targetPort: 22000
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
    route:
      app:
        hostnames: ["sync.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8384
    persistence:
      # TODO: volsync
      config:
        type: persistentVolumeClaim
        suffix: config
        size: 1Gi
        storageClass: linbit-replicated
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /config
      data:
        type: persistentVolumeClaim
        size: 8Gi
        storageClass: linbit-local
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /var/syncthing