apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-manga
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: linbit-nfs
  volumeMode: Filesystem
  volumeName: pvc-670213f5-902d-4fe0-b4e7-27913e2968f7
