---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: prowlarr-secret
  data:
      - secretKey: PROWLARR__AUTH__APIKEY
        remoteRef:
          key: cephiro/prowlarr
          property: prowlarr__auth__apikey
