apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: annotate-kopiur-mover
spec:
  rules:
    - name: add-annotation
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - downloads
              selector:
                matchLabels:
                  app.kopiur.io/component: mover
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              setGateway: "false"
