---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-s3-kopiur
  namespace: network
spec:
  hostnames:
    - kopiur.s3.musai.ovh
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /kopiur
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              # Rewrite Kopia’s virtual-host request:
              #   /<object>
              # into Garage’s path-style:
              #   /v1/s3/kopiur/<object>
              type: ReplacePrefixMatch
              replacePrefixMatch: "/v1/s3/kopiur"
      backendRefs:
        - name: garage
          namespace: storage
          port: 3900
---
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: storage
  labels:
    app: garage
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.99.19
  ports:
    - name: s3
      port: 3900
      targetPort: 3900
