---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
# This policy is to allow inbound SMB traffic to the Samba pod
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: samba-ingress
  labels:
    app.kubernetes.io/instance: &instance samba
    app.kubernetes.io/name: &name samba
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: *instance
      app.kubernetes.io/name: *name
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "445"
              protocol: TCP
            - port: "445"
              protocol: UDP
            - port: "3702"
              protocol: TCP
            - port: "3702"
              protocol: UDP
            - port: "5355"
              protocol: TCP
            - port: "5355"
              protocol: UDP