apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: downloads
stringData:
    samba.yaml: ENC[AES256_GCM,data:T6oxzHajeB4aUjpCwTVmWYuvmOgOoTBVJBeCsfsTnyl8XYRSTrdajjKORiTXhJ8cQcmdd/fhm3ZAO5yXeuSMd+ikLL0PZCT9rxbAP7VscKmjYxgxnxZS/oQIlXNQnBTDBwaMcCy2RJOb44VCNV2kXvTiVrZsoLNfxDn8wERPtrwUu5WiAPoiPgaMsGbVSb6p85CJSpaQNfzUSdwa/Af+BGyPNuZcvanfxxzbWSiP16D4v6+S5RJ1cLdhpiwTTuTg9WnTuRTOi+eKzq1iJ4m0p3TGY0Be0CUgf9CE+Fy+bj71tni1MAofU/k0ue0yvEPrew8vBaLufewLAphq7LhSib5ai2X9Ps5xo5sk3sz+VemgchPJPck1Zs9aloEXwkEMtIBJ10t5LFDz9fz2cakToIVmPo+DRWWIPm4O6UkjZF9lgxj6VkQ+Pl76Cw7uympbV2glbM7LZg2oD71HmlrdFMxmeu6/XbGZqLXG1QZCMXMAMBZexuzOBfQ5QqDyWpY043pbU08JcjHOKmXfskMkLR2qFJgy8BcKkQPR8tWmutbsVY5PnZMqvW3V51SxSjP1cCLjoFXEXE348lZYl1v9lOHmaOpmiL/ifXiQyDZlooic5irqXt6BG41WzzCiWWAgZVzWa24dRS8zps45Z5YoosSUehdijXXms2VqsMA8smDTFYoRRxcwYqA9Vy5PtvELVEN9fOM=,iv:FBCIDdUwuXgWI4OkUzOp/UW8fp0Q/R/LXdM+F7CZkvQ=,tag:vc58KPTVUmrgsYwxdkPAlw==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T10:11:55Z"
    mac: ENC[AES256_GCM,data:OrAE1dFZqojxt5kfugip3I6nxYZ6VsmHZI78P1zWxY3je+OcFroq6/UYs7t71EATPGw2Ljgiv1Z3PZxwLD6AS2QhfRcXEWS0e1PVFaJ6t2hz3TxKtuyGOc4fTkFUqJNdjtYFnOap2QgqBzDmD/KnZd9/MxcAcqir5rKu17HGa1o=,iv:JgakLfl9Nku2d+fYpnJYbrxFv+FK1sWJpniGEUUybGU=,tag:IT/N6dWKm28bRb5MOZSozQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
