apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: downloads
stringData:
    samba.yaml: ENC[AES256_GCM,data:r8NTwTcEhbko6XptFSgavSS4yXBpJlYp8YCdNOwttgzKuDOSVrpaYqdkmbsTnebDBbPaotLgTz1bipe168FZx8Dv+7rmENHjjQiMxqRmoU0NWwzYzgFn8uUkrFa4Pu8tTgsV2l4MPwcJwkSmHyxeivvT89gcdb4dVmRWdEEsNQFQH9H781ymYKN+rqKjdigUkNUeXqHTZQNVnYjJW+sVBq77E7z7gQKY1bWQrPCySuLNUVHJ4+0nONN/l4K47a/aGYbgJrT3j86Kb+D6fqxAOGiQyZHpM/KyBQ4bzyO1MGo5yyqDju+ybEO0ZZ/0k7U7+1b8JAPiCkuQg1yjDDz9ECwGcI7SfdCUOjkc/fw5b0ygGrbUSO2UCPSoKOJEQ6JpJSZQZRzL47/RjvppaYq1CS22XkIUO/dDp0dV+28LPojjrjC3NLnq/r4KHEOGlZ8oJMtCgE/GsFpjSbDC5qUh9kUICDjDEj+/ruzLviWMQb+1Bpax9LaRunhc5C25qSrIqjXpzOcBlgQkcmaZHbYRPkcJyZ7bF9En4tm10LKU/2irXxTR1LZICXZX7xeizL/4snJYyZOjaJQ8XuluxiBvjTX5lrb/6XT6yaMTMynvtCnDQvuBw/+DNgABFZg9Rj6v9vsXUcIJTp5UDnVyFlzJW6bGJh9flfDzVtRBNOlilGvkwtgnmcLXLEx808ECJt0W44AlSno6Yst2WhXhKxTwOgPKzfMJ5apvFao4Ekl4GiM+VI/Sp+KziFtpVn26xLJ6wb/ymQVeaphzIuCC17cTWwmxm76MrPM=,iv:NSMbecnN6LffBoHt5mQfaA1YLQ6VRReCSsI6//VOadw=,tag:v5qFUkDKFxSx812rLqovyA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T10:40:44Z"
    mac: ENC[AES256_GCM,data:JLUGNnzXcd7Viv6bSxPpMivN8QgrEpd7HbhafGe2hzGq7ISfizJrKzQcHdMxSu4CAH1ahTmKG/yL50D+jLvgrrX/i0waToyoAwfprFdIL2a8vKA581T5G1pBWWXZTr3j45rGPy8zjCOXkLBz4aC+5+jUx1v5nyIe8RvctumIBRY=,iv:Fgbb9IdFRo1IfBawC4tTLdRKmTro62pUBxiIoyemqQg=,tag:onCp1+e0XQZ6h1llNM1z8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
