apiVersion: v1
kind: Secret
metadata:
    name: samba-1
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:FlNp18i774sVsOP9A4ATB1QgaxW8D52fGskrb4Hy0awu64OFBIkwCkrnNVjR6acHHoeYYtjm+JDj+SNSZJw2wqsN4Ixj7GuRJM8+GdD3zFFh9fcAkTXcME1Z7Cm9ofxlQM22ZApV6jj5UFR0zIXAxA6fi0sYx6Ap88rD+VAn0ohne2N28n5Lv/oPe51rEWqH1RduMGP/CesdhYD+ZRgxHublW/b4ZvXjkw9orkJWcv1yAZzP+peVGOUJzAUIA0RfWCZzW+qWa9ho8AB891T83y54IOkxb1k9zSoja9+HJ+hN8jzO2VghCohe46mQimX4f4zP7djaAjhnZSmQIY/vqz8n17VyFVXXi6d03ssFHrtHS5LZJW7gxC1Qp1NE1tp5nR6Mk/ueFAO2cmYXFN9MOWedCXz7eOvj0YtQK6fSgrOS5aSok96YSPkFOXQ4OrDAQTAftzO4WEMqFtE8c9xt3TmMLkSfQmZ8eOETJQp/Jnl7pakU9l7/E1cSDdDCABB2r22K9290EftC8EVCbMvmWNo7wWxcXLyudp1FGR2cR7MdbJirPPWo2cG3nDWhs2ZQpSDpTi9JBt9Y0XQPNbYoLMoaDly34dR3LAJEdmjz9uhfRGzjWqaC6PNlqO4ng5dA2tbRGND1wFiElD9A0QW7t+ej++p5rdNacTV8ITWrzXds6seg7joe1Z1xxJ+zMY2d8G6T4HG3oWQlRGRCfe3nkIuU6IYdLS+XVVqRNXKLO3ZIOCUNiRBRFVabzmyCidT3GLSz46BWLbpBchMcOn6GGBpUkHdvIBPu9hhjn9KAYXMvnzoz6ws0AuBro47Nkyru2LHZq7RK4Uhck8MwV5fsJLzxxQv1qSukYiPQvepG0BHfgVX85FY5R/Rj1hktnNY8+nOrmxOpJDbj0nDDUEJByoXvYzn4UsCSH+AQbh/9dN+YrYCpoLpJFx5BYP6XT2x7sCqSvdWgrZKWttdbDoroO6PIZBclo3fcd5jjWg==,iv:QvJKi1cxwnPmGVzhond28hLEjkqrkGMwsBsQt95Qwdc=,tag:PEAVsheb0BLvUJzbgT8psw==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T19:39:47Z"
    mac: ENC[AES256_GCM,data:6Is8mFncecHOzd8cX1ix85sQ8upzqi5mpMKMeM07UzU580kPYHOanqcMD43JEw+Q88SZG4s73Jr5wMkJ6wyU3x7s+hnAsTgho7n+tUpdJt3VSkXGtNMfs6cmW8R5Yxb6JtLeSqXuJy2X3NJ7tj4qQw4lI/99cerT0ZSpcuyXJv8=,iv:DNivwA56F7GaH2FZvUkUo+i6w3d8uVOhR+68a3FOFw4=,tag:gTJCsNe1WNvco8NZG9lZag==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
