---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: syncthing-dst
  resources:
    requests:
      storage: 1050Gi
  storageClassName: linbit-local
