# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.99.60:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.99.60"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "hikaru-01"
    ipAddress: "192.168.99.20"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ed8f512419f9237e2ee8a61b0323774dd935fdd41d51f33acf41f2df68517432
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:8a:dd:99"
        dhcp: false
        addresses:
          - "192.168.99.20/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.99.1"
        mtu: 1500
        vip:
          ip: "192.168.99.60"
  - hostname: "fuu-01"
    ipAddress: "192.168.99.21"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ed8f512419f9237e2ee8a61b0323774dd935fdd41d51f33acf41f2df68517432
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b8:a4:cf"
        dhcp: false
        addresses:
          - "192.168.99.21/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.99.1"
        mtu: 1500
        vip:
          ip: "192.168.99.60"
  - hostname: "umi-01"
    ipAddress: "192.168.99.22"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ed8f512419f9237e2ee8a61b0323774dd935fdd41d51f33acf41f2df68517432
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:85:18:3c"
        dhcp: false
        addresses:
          - "192.168.99.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.99.1"
        mtu: 1500
        vip:
          ip: "192.168.99.60"

# Global patches
patches:
  - "@./patches/global/machine-drbd.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-interface.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

