# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tranga-website
spec:
  chartRef:
    kind: OCIRepository
    name: tranga-website
  interval: 15m
  values:
    controllers:
      tranga-website:
        pod:
          annotations:
            setGateway: "false"
        containers:
          app:
            image:
              repository: glax/tranga-website
              tag: latest
            ports:
              - name: http
                containerPort: 80
            env:
              API_URL: http://tranga-api:6531
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 300m
                memory: 512Mi

            probes:
              liveness:
                enabled: true
                path: /
                port: http

              readiness:
                enabled: true
                path: /
                port: http

    service:
      tranga-website:
        controller: tranga-website
        ports:
          http:
            port: 80
