---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name komf-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    creationPolicy: Owner
  data:
      - secretKey: KOMF_KOMGA_USER
        remoteRef:
          key: cephiro/komga
          property: komf_komga_user
      - secretKey: KOMF_KOMGA_PASSWORD
        remoteRef:
          key: cephiro/komga
          property: komf_komga_password
      - secretKey: KOMF_KAVITA_API_KEY
        remoteRef:
          key: cephiro/kavita
          property: komf_kavita_api_key

