# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: syncthing
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
    persistence:
      enabled: true
      existingClaim: syncthing-pv-claim
      mountPath: /var/syncthing
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
    service:
      enabled: true
      type: ClusterIP
      services:
        dashboard:
          enabled: true
          name: syncthing-dashboard
          port: 8384
          targetPort: 8384
          protocol: TCP
        protocol:
          enabled: true
          name: syncthing-protocol
          ports:
            - name: syncthing-tcp
              port: 22000
              protocol: TCP
              targetPort: 22000
            - name: syncthing-udp
              port: 22000
              protocol: UDP
              targetPort: 22000
            - name: syncthing-disc
              port: 21027
              protocol: UDP
              targetPort: 21027
    statefulset:
      enabled: true
      serviceName: syncthing
      terminationGracePeriodSeconds: 60