apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:NfAHTcAKc3Hn,iv:IwYK40Sq+wh6nEx8YOCvuYiWEXz3PJAPOPGral5ExuY=,tag:xec9sXhYLA16okCopuD0Cg==,type:str]
sops:
  age:
    - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ1hTV0pzcVdrVS9WWk9o
        L0hTU0F0cElVNWdiTloxT3JKRWFUT0UvRUNrCndpSFFFQVpuK1NxdzROM2Vra0Fi
        TVBIbXZzdDQyN0ttUlFXbE9mSDlHL3MKLS0tIFlSOWdvckg4RFhxK2JoYVdNb0Nj
        R2dXZms3aVdXVlpra0hFWlBWNzYvUjAK1DOIQAPW2dHjwdAqjLJ1Tcrl1GtRctzX
        tyTz+XFG3RKUev3ETW3JzaN+f66wFLjUbo1TlzzcN8MMrC3zqykOxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-12T18:39:29Z"
  mac: ENC[AES256_GCM,data:wlayhygNUUb5deb+JKrspVIXyFVWKjpDYFvAJEN1LmSqHnIQVJJJo78whlHWZxfL+8TwyxxKGyktt1q29e20xwoAUxDzj2VgpHoFPMkJB7+lrCcyfn8X0Q8JrfuZzORjSsqHU/HWOLJO5oB7vbS9iFFF0U4LbZ5IiePb7b/VnkE=,iv:hvVUzi4wnGjUj5iHG/hJy6LaEJ2AWXKmhtF29qE0TEY=,tag:O+dVFcbTGrFrjLxoO4MSjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
